### PR TITLE
Use basename of ext name as target filename

### PR DESCRIPTION
**Pull request by mrkn**
As mkmf's create_makefile extracts the basename of the given extension name with directory prefixes, I want to make rake-compiler doing so.

### CODE REVIEW

**Comment by kou** [comment]
Could you show an example that shows differences with this change?

**Comment by mrkn** [comment]
The following output is the result of examples I added in the commit 76d7201 executed on the head of the current master branch.

I think you can understand the differences with this change by checking it.

```
Run options: include {:locations=>{"./spec/lib/rake/extensiontask_spec.rb"=>[273]}}
FFFF

Failures:

  1) Rake::ExtensionTask (tasks) (one extension whose name with directory prefixes) tmp/{platform}/prefix1/prefix2/extension_one/{ruby_ver}/extension_one.{so,bundle} should define as task
     Failure/Error: Rake::Task.task_defined?("tmp/#{@platform}/prefix1/prefix2/extension_one/#{@ruby_ver}/#{@ext_bin}").should be_true
       expected false to be true
     # ./spec/lib/rake/extensiontask_spec.rb:284:in `block (5 levels) in <top (required)>'

  2) Rake::ExtensionTask (tasks) (one extension whose name with directory prefixes) tmp/{platform}/prefix1/prefix2/extension_one/{ruby_ver}/extension_one.{so,bundle} should depend on 'tmp/{platform}/prefix1/prefix2/extension_one/{ruby_ver}/Makefile'
     Failure/Error: Rake::Task["tmp/#{@platform}/prefix1/prefix2/extension_one/#{@ruby_ver}/#{@ext_bin}"].prerequisites.should include("tmp/#{@platform}/prefix1/prefix2/extension_one/#{@ruby_ver}/Makefile")
     RuntimeError:
       Don't know how to build task 'tmp/x86_64-darwin14/prefix1/prefix2/extension_one/2.3.0/extension_one.bundle' (see --tasks)
     # ./spec/lib/rake/extensiontask_spec.rb:288:in `block (5 levels) in <top (required)>'

  3) Rake::ExtensionTask (tasks) (one extension whose name with directory prefixes) tmp/{platform}/prefix1/prefix2/extension_one/{ruby_ver}/extension_one.{so,bundle} should depend on 'ext/extension_one/source.c'
     Failure/Error: Rake::Task["tmp/#{@platform}/prefix1/prefix2/extension_one/#{@ruby_ver}/#{@ext_bin}"].prerequisites.should include("ext/prefix1/prefix2/extension_one/source.c")
     RuntimeError:
       Don't know how to build task 'tmp/x86_64-darwin14/prefix1/prefix2/extension_one/2.3.0/extension_one.bundle' (see --tasks)
     # ./spec/lib/rake/extensiontask_spec.rb:292:in `block (5 levels) in <top (required)>'

  4) Rake::ExtensionTask (tasks) (one extension whose name with directory prefixes) tmp/{platform}/prefix1/prefix2/extension_one/{ruby_ver}/extension_one.{so,bundle} should not depend on 'ext/extension_one/source.h'
     Failure/Error: Rake::Task["tmp/#{@platform}/prefix1/prefix2/extension_one/#{@ruby_ver}/#{@ext_bin}"].prerequisites.should_not include("ext/prefix1/prefix2/extension_one/source.h")
     RuntimeError:
       Don't know how to build task 'tmp/x86_64-darwin14/prefix1/prefix2/extension_one/2.3.0/extension_one.bundle' (see --tasks)
     # ./spec/lib/rake/extensiontask_spec.rb:296:in `block (5 levels) in <top (required)>'

Finished in 0.00758 seconds
4 examples, 4 failures
```

**Comment by mrkn** [comment]
In addition, the task `tmp/#{@platform}/prefix1/prefix2/extension_one/#{@ruby_ver}/prefix1/prefix2/#{@ext_bin}` is defined instead of the expected task in the current master branch.

**Comment by kou** [comment]
Thanks. I'll merge this pull request after Travis CI reports "success".

**Comment by kou** [comment]
I've merged.

**Pull request merged**
